services:
  - type: web
    name: label-verification-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
